-- MySQL Script generated by MySQL Workbench
-- Thu May  9 10:34:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employer` (
  `idEmployer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmployer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` INT NOT NULL,
  `FAX` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `idBrand` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idBrand`),
  INDEX `fk_Brand_Supplier1_idx` (`Supplier_idSupplier` ASC),
  CONSTRAINT `fk_Brand_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `registrationdate` DATETIME NOT NULL,
  `recommended by?` INT NULL,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customer_Customer1_idx` (`recommended by?` ASC),
  CONSTRAINT `fk_Customer_Customer1`
    FOREIGN KEY (`recommended by?`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Frame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Frame` (
  `idFrame` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  `colour` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idFrame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colour` (
  `idColour` INT NOT NULL,
  `colour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColour`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LeftGlass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LeftGlass` (
  `idLeftGlass` INT NOT NULL,
  `prescription` DECIMAL(2,2) NOT NULL,
  `Colour_idColour` INT NOT NULL,
  PRIMARY KEY (`idLeftGlass`),
  INDEX `fk_LeftGlass_Colour1_idx` (`Colour_idColour` ASC),
  CONSTRAINT `fk_LeftGlass_Colour1`
    FOREIGN KEY (`Colour_idColour`)
    REFERENCES `mydb`.`Colour` (`idColour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RightGlass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RightGlass` (
  `idRightGlass` INT NOT NULL,
  `prescription` DECIMAL(2,2) NOT NULL,
  `Colour_idColour` INT NOT NULL,
  PRIMARY KEY (`idRightGlass`),
  INDEX `fk_RightGlass_Colour1_idx` (`Colour_idColour` ASC),
  CONSTRAINT `fk_RightGlass_Colour1`
    FOREIGN KEY (`Colour_idColour`)
    REFERENCES `mydb`.`Colour` (`idColour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `idGlasses` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `Brand` INT NOT NULL,
  `Frame` INT NOT NULL,
  `LeftGlass` INT NOT NULL,
  `RightGlass` INT NOT NULL,
  `sold by?` INT NOT NULL,
  `Customer` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  INDEX `fk_Glasses_Employer1_idx` (`sold by?` ASC),
  INDEX `fk_Glasses_Brand1_idx` (`Brand` ASC),
  INDEX `fk_Glasses_Customer1_idx` (`Customer` ASC),
  INDEX `fk_Glasses_Frame1_idx` (`Frame` ASC),
  INDEX `fk_Glasses_LeftGlass1_idx` (`LeftGlass` ASC),
  INDEX `fk_Glasses_RightGlass1_idx` (`RightGlass` ASC),
  CONSTRAINT `fk_Glasses_Employer1`
    FOREIGN KEY (`sold by?`)
    REFERENCES `mydb`.`Employer` (`idEmployer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Brand1`
    FOREIGN KEY (`Brand`)
    REFERENCES `mydb`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Customer1`
    FOREIGN KEY (`Customer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Frame1`
    FOREIGN KEY (`Frame`)
    REFERENCES `mydb`.`Frame` (`idFrame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_LeftGlass1`
    FOREIGN KEY (`LeftGlass`)
    REFERENCES `mydb`.`LeftGlass` (`idLeftGlass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_RightGlass1`
    FOREIGN KEY (`RightGlass`)
    REFERENCES `mydb`.`RightGlass` (`idRightGlass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Frame`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Frame` (`idFrame`, `type`, `colour`) VALUES (1, 'Flotant', DEFAULT);
INSERT INTO `mydb`.`Frame` (`idFrame`, `type`, `colour`) VALUES (2, 'Pasta', DEFAULT);
INSERT INTO `mydb`.`Frame` (`idFrame`, `type`, `colour`) VALUES (3, 'Metalica', DEFAULT);

COMMIT;

